name: Go Build and Test

on:
  workflow_call:
    inputs:
      go-enabled:
        default: false
        required: false
        type: boolean
      go-build-pattern:
        required: false
        type: string
      go-test-pattern:
        default: './...'
        required: false
        type: string
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-go:
    if: ${{ inputs.go-enabled }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Download Dependencies
        run: go mod download

      - name: Build Project
        if: ${{ inputs.go-build-pattern != '' }}
        run: go build ${{ inputs.go-build-pattern }}

      - name: Run Tests
        if: ${{ inputs.go-test-pattern != '' }}
        run: go test -race -v ${{ inputs.go-test-pattern }}
