name: goreleaser

on:
  push:
    tags:
      - "*"
  workflow_call:
    secrets:
      gpg_private_key:
        description: "The GPG key to be used to sign releases"
        required: true
      passphrase:
        description: "Passphrase for the gpg key"
        required: true
      release_github_token:
        description: "Github token required for creating the release on the repo"
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
          gpg_private_key: "${{ secrets.gpg_private_key }}"
          passphrase: "${{ secrets.passphrase }}"
          trust_level: 5
      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version-file: 'go.mod'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@4247c53b304edb39a4e6a0808f415d3eebad450a
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.release_github_token }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
