# This workflow requires a secret "secrets.RENOVATE_GITHUB_TOKEN" to be defined in the repo that it's executed against.

name: Renovate

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: { }
  workflow_call:
    inputs:
      target_repo:
        description: "The repository that the workflow will run on. This needs to be of form '<org>/<repo_name>'"
        type: string
        required: true
      renovate_config_file:
        description: "The json file that provides specific configuration for the repository"
        type: string
        required: false
        default: "renovate.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.0
        with:
          token: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          configurationFile: ${{ inputs.renovate_config_file }}
        env:
          RENOVATE_AUTODISCOVER_FILTER: ${{ inputs.target_repo }}
          RENOVATE_AUTODISCOVER: true
          LOG_LEVEL: info
